---
- name: Download
  get_url:
    url: "{{ scala_download_url }}"
    dest: /tmp/scala-{{ scala_version }}.tgz

- name: Unpack
  unarchive:
    src: /tmp/scala-{{ scala_version }}.tgz
    dest: /opt
    owner: "{{ sys_user }}"
    remote_src: yes

- name: Create symbolic link 
  file:
    src: "{{ scala_home }}-{{ scala_version }}"
    dest: "{{ scala_home }}"
    force: yes
    state: link

- name: Env
  template: 
    src: etc/profile.d/scala.sh
    dest: /etc/profile.d/scala.sh
    owner: "{{ sys_user }}"
    group: "{{ sys_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - env